namespace ThreatLocker.Shared.Constants.Ops
{
    public enum OpsActionDataFieldType
    {
        RestAPIMethod = 1,
        RestAPIURL = 2,
        RestAPIContentType = 3,
        RestAPIHeaders = 4,
        RestAPIBody = 5,
        WebhookMethod = 6,
        WebhookURL = 7,
        WebhookContentType = 9,
        WebhookHeaders = 10,
        WebhookBody = 11,
        AlertSeverity = 12,
        AlertSummary = 13,
        AlertDetails = 14,
        EmailRecipients = 15,
        EmailSubject = 18,
        EmailBody = 19,
        EnableApplicationPolicyId = 41,
        DisableApplicationPolicyId = 42,
        EnableStoragePolicyId = 43,
        DisableStoragePolicyId = 44,
        EnableNetworkPolicyId = 45,
        DisableNetworkPolicyId = 46,
        IncreaseThreatLevel = 50,
        IsolateMachine = 51,
        LockdownMachine = 60,
        AlertThreatLevel = 61,
        KaseyaTicketSubject = 62,
        KaseyaTicketBody = 63,
        DattoTicketSubject = 64,
        DattoTicketBody = 65,
        ConnectwiseTicketSubject = 66,
        ConnectwiseTicketBody = 67,
        PushNotificationAdministrators = 68,
        ServiceNotes = 69,
        RestAPIClientMethod = 70,
        RestAPIClientURL = 71,
        RestAPIClientContentType = 72,
        RestAPIClientHeaders = 73,
        RestAPIClientBody = 74,
        WebhookClientMethod = 75,
        WebhookClientURL = 76,
        WebhookClientContentType = 77,
        WebhookClientHeaders = 78,
        WebhookClientBody = 79,
        CyberHeroDetectionAndResponse = 80,
    }
}
